[2024-08-18T12:01:12.398+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-18T12:01:12.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_values_TS_36.get_deaths_dataset.insert_data_to_db scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-18T12:01:12.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_values_TS_36.get_deaths_dataset.insert_data_to_db scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-18T12:01:12.424+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-18T12:01:12.436+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): get_deaths_dataset.insert_data_to_db> on 2024-08-11 00:00:00+00:00
[2024-08-18T12:01:12.445+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1262) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-18T12:01:12.446+0000] {standard_task_runner.py:63} INFO - Started process 1302 to run task
[2024-08-18T12:01:12.446+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'predict_values_TS_36', 'get_deaths_dataset.insert_data_to_db', 'scheduled__2024-08-11T00:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp0fi91s8c']
[2024-08-18T12:01:12.448+0000] {standard_task_runner.py:91} INFO - Job 246: Subtask get_deaths_dataset.insert_data_to_db
[2024-08-18T12:01:12.479+0000] {task_command.py:426} INFO - Running <TaskInstance: predict_values_TS_36.get_deaths_dataset.insert_data_to_db scheduled__2024-08-11T00:00:00+00:00 [running]> on host a571e3af8ef8
[2024-08-18T12:01:12.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ruslan Solarev' AIRFLOW_CTX_DAG_ID='predict_values_TS_36' AIRFLOW_CTX_TASK_ID='get_deaths_dataset.insert_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-11T00:00:00+00:00'
[2024-08-18T12:01:12.543+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-18T12:01:12.550+0000] {sql.py:276} INFO - Executing: None
[2024-08-18T12:01:12.557+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-08-18T12:01:12.558+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-18T12:01:12.559+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2024-08-18T12:01:12.565+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=predict_values_TS_36, task_id=get_deaths_dataset.insert_data_to_db, run_id=scheduled__2024-08-11T00:00:00+00:00, execution_date=20240811T000000, start_date=20240818T120112, end_date=20240818T120112
[2024-08-18T12:01:12.573+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 246 for task get_deaths_dataset.insert_data_to_db (List of SQL statements is empty; 1302)
[2024-08-18T12:01:12.619+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-18T12:01:12.629+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-18T12:01:12.632+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
